import Head from 'next/head';
//import { Auth } from '@supabase/auth-ui-react';
//import { User } from '@supabase/supabase-js';
//import { SupabaseClient } from '@supabase/supabase-js';
//import { ThemeSupa } from '@supabase/auth-ui-shared';
import { createClient } from '@/lib/supabase/server';
//import { getUser } from '@/lib/supabase/queries';
import { supabase as supabaseClient } from '@/lib/supabase/init';
import QuestionList from '@/components/QuestionList';

import '@/styles/app.css';
  

export default async function App() {
  const supabase = createClient();
  const {
    data: { user }
  } = await supabase.auth.getUser();

  return (
    <>
      <Head>
        <title>Bioverse App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full bg-200">
        {user && (
          <div
            className="w-full h-full flex flex-col justify-center items-center p-4"
            style={{ minWidth: 250, maxWidth: 600, margin: 'auto' }}
          >
            <QuestionList user={user} />
            <button
              className="btn-black w-full mt-12"
              onClick={async () => {
                const { error } = await supabaseClient?.auth?.signOut();

                if (error) {
                  console.log('Error logging out:', error.message);
                }
              }}
            >
              Logout
            </button>
          </div>
        )}
      </div>
    </>
  );
}