import { redirect } from 'next/navigation';
import Head from 'next/head';
//import { Auth } from '@supabase/auth-ui-react';
//import { User } from '@supabase/supabase-js';
//import { SupabaseClient } from '@supabase/supabase-js';
//import { ThemeSupa } from '@supabase/auth-ui-shared';
import { createClient } from '@/lib/supabase/server';
//import { getUser } from '@/lib/supabase/queries';
//import { supabase as supabaseClient } from '@/lib/supabase/init';
//import { getUser } from '@/controllers/user';
import Questionnaires from '@/components/Questionnaires';
import { getURL } from '@/utils/helpers';

import '@/styles/app.css';
  

export default async function App() {
  const supabase = await createClient();

  const {
    data: { user }
  } = await supabase.auth.getUser();

  console.log(user)

  if (!user) {
    return redirect('/signin');
  }

  return (
    <>
      <Head>
        <title>Bioverse App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={getURL("/favicon.ico")} />
      </Head>
      <div className="w-full h-full bg-200">
        {user && (
          <div
            className="w-full h-full flex flex-col justify-center items-center p-4"
            style={{ minWidth: 250, maxWidth: 600, margin: 'auto' }}
          >
            <Questionnaires />
          </div>
        )}
      </div>
    </>
  );
}